/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */
import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import type * as actions_generateInsights from "../actions/generateInsights.js";
import type * as auth from "../auth.js";
import type * as http from "../http.js";
import type * as mutations_saveBodyMeasurement from "../mutations/saveBodyMeasurement.js";
import type * as mutations_saveChatMessage from "../mutations/saveChatMessage.js";
import type * as mutations_uploadDataset from "../mutations/uploadDataset.js";
import type * as queries_getCurrentUser from "../queries/getCurrentUser.js";
import type * as queries_getInsights from "../queries/getInsights.js";
import type * as queries_getLatestDataset from "../queries/getLatestDataset.js";
import type * as queries_getWorkoutSets from "../queries/getWorkoutSets.js";

declare const fullApi: ApiFromModules<{
  "actions/generateInsights": typeof actions_generateInsights;
  auth: typeof auth;
  http: typeof http;
  "mutations/saveBodyMeasurement": typeof mutations_saveBodyMeasurement;
  "mutations/saveChatMessage": typeof mutations_saveChatMessage;
  "mutations/uploadDataset": typeof mutations_uploadDataset;
  "queries/getCurrentUser": typeof queries_getCurrentUser;
  "queries/getInsights": typeof queries_getInsights;
  "queries/getLatestDataset": typeof queries_getLatestDataset;
  "queries/getWorkoutSets": typeof queries_getWorkoutSets;
}>;
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
